sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script: npm run validate
after_success: kcd-scripts travis-after-success
branches:
  only:
    - master
